/*
 * Copyright 2020 Lewis Liu. All Rights Reserved.
 */
package com.lelib.ycyocp.model;

import com.lelib.ycyocp.producer.YcyProducer;

/**
 * The abstract Product. All the product generated by the {@link YcyProducer} should extend this model.
 */
public abstract class Product {
    /**
     * The string format that represents the product.
     *
     * @return
     */
    public abstract String stringify();

    @Override
    public String toString() {
        return this.stringify();
    }
}
