/*
 * Copyright 2020 Lewis Liu. All Rights Reserved.
 */
package com.lelib.ocp.xad.consumer;

import com.lelib.ocp.xad.model.ConsumeResult;
import com.lelib.ocp.xad.model.Product;
import com.lelib.ocp.xad.producer.XadProducer;

/**
 * The consumer interface, which will be used to consume the {@link Product}
 * which is expected to be generated by {@link XadProducer}.
 *
 * @param <TProduct>
 * @param <TConsumeResult>
 */
public interface XadConsumer<TProduct extends Product, TConsumeResult extends ConsumeResult> {
    /**
     * Consume the product then return the consuming result.
     *
     * @param product
     * @return
     */
    TConsumeResult consume(TProduct product);
}
