/*
 * Copyright 2020 Lewis Liu. All Rights Reserved.
 */
package com.lelib.ocp.xad.model;

import com.lelib.ocp.xad.producer.XadProducer;

/**
 * The abstract Product. All the product generated by the {@link XadProducer} should extend this model.
 */
public abstract class Product {
    /**
     * The string format that represents the product.
     *
     * @return
     */
    public abstract String stringify();

    @Override
    public String toString() {
        return this.stringify();
    }
}
